name: Deploy to Production

on:
  push:
    branches: [ main ]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            if [ ! "$(docker ps -q -f name=redis)" ]; then
              if [ "$(docker ps -aq -f status=exited -f name=redis)" ]; then
                docker rm redis
              fi
              docker run -d --name redis -p 6379:6379 redis
            fi

            cd /home/mkravchenko/nest-movie-app
            git pull origin main
            npm ci
            npm run build
            npm run typeorm:migration:run

            pm2 delete nest-movie || true
            pm2 start /home/mkravchenko/nest-movie-app/dist/main.js --name nest-movie